[package]
name = "i18n-linter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0", features = []}
grep = { version = "0.3.1" }
ignore = { version = "0.4" }